x-app-service: &app-service
  image: fuel-hunter-app
  env_file:
    - .env
  volumes:
    - .:/code

services:
  postgres:
    image: postgres:16
    container_name: fh-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  tg-bot:
    <<: *app-service
    build:
      context: .
      dockerfile: docker/app.Dockerfile
      target: app
    container_name: fh-tg-bot
    command: sh -c "alembic upgrade head && python src/tg_bot/run.py"
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fh-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always
    ports:
      - "${RABBITMQ_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    <<: *app-service
    container_name: fh-worker
    command: celery --app src.celery.celery_app worker --pool threads --loglevel INFO
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  beat:
    <<: *app-service
    container_name: fh-beat
    command: celery --app src.celery.celery_app beat --loglevel=INFO
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
  postgres_data:
