"""initial

Revision ID: 708ef22f47f0
Revises: 
Create Date: 2026-07-18 22:14:37.215174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708ef22f47f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(precision=53), nullable=False),
    sa.Column('lon', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('telegram_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk_telegram_users'))
    )
    op.create_table('stations',
    sa.Column('osm_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('yes', 'no', 'queue', 'low', name='station_status'), nullable=True),
    sa.Column('confidence_base', sa.Float(), nullable=False),
    sa.Column('fuels_now', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), nullable=True, comment='UTC time when the sync beat task synchronized this station.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC time when this station was updated on the source website.'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stations_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('osm_id', name=op.f('pk_stations'))
    )
    op.create_table('user_station_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_osm_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['station_osm_id'], ['stations.osm_id'], name=op.f('fk_user_station_subscriptions_station_osm_id_stations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.telegram_id'], name=op.f('fk_user_station_subscriptions_telegram_user_id_telegram_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_station_subscriptions')),
    sa.UniqueConstraint('station_osm_id', 'telegram_user_id', name=op.f('uq_user_station_subscriptions_station_osm_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_station_subscriptions')
    op.drop_table('stations')
    op.drop_table('telegram_users')
    op.drop_table('locations')
    # ### end Alembic commands ###
